### ISSUE TITLE
renegotiate offer for remote stream.

### ISSUE THREAD

**Issue by rabiea** [zevarito/Licode-ErizoClientIOS#47]
@zevarito i want to turn video of remote stream off/on (not get video packets altogether when video is turned off). How can i renegotiate ?

**Comment by zevarito** [comment]
@rabiea I am afraid that is not possible right now, you need to unsubscribe and subscribe to the stream again.

**Comment by ashar02** [comment]
@zevarito is it not supported on this repository or Licode does not support renegotiation / reconfiguration?

**Comment by zevarito** [comment]
@ashar02 @rabiea,

Licode give support to that since this[0] commit I believe, a search of `muteStream`[1] across Licode repo shows how it is implemented and how it can be used, it relies on `updateConfiguration` API, there is also a `muteAudio` API call in Licode's client as a shortcut for that, while I am not seeing an equivalent for Video I belive `updateConfiguration` + `muteStream` handle both cases.

I *think*, and I haven't read the full commit yet, it is not a re-negotiation per-se, I mean there is not candidates involved and SDP exchanges, I think it is only the MCU not forwarding packets back to the client.

Now, back to this library to make it work here, we need to implement `updateConfiguration` for `ECStream` which should not be trivial at all in the sense that it only implies a couple of new signaling messages. I am not in rush to handle this but is something that definitely needs to be addressed cause many Licode features are enabled/disabled by that API. If one of you is up to start working right now on this I am up to have a call to revisit source code and discuss the best way to do it. Let me know!

[0] https://github.com/lynckia/licode/commit/bdbf8873e9ea66cb4146b79bb47daabc60a965b6
[1] https://github.com/lynckia/licode/search?q=muteStream&type=Code&utf8=%E2%9C%93
