### ISSUE TITLE
Crash on RTCMediaStream dealloc

### ISSUE THREAD

**Issue by gluckMu** [zevarito/Licode-ErizoClientIOS#48]
Hi, @zevarito , 
    I use a UINavigationController as my app root controller, and push a controller A(same as MultiConferenceViewController in your example project)  when click a button on previous controller.  It is ok to present controller A.  

The viewDidLoad of controller A 
- (void) viewDidLoad {
    localStream_ = [[ECStream alloc] initLocalStream];
    if ([localStream_ hasVideo]) {
        RTCVideoTrack *videoTrack = localStream_.mediaStream.videoTracks[0];
        [videoTrack addRenderer:self.localView];
    }
}

And then we do nothing and click the back button instantly, app crashed on dealloc of controller A. And I found that there is a EXC_BAD_ACCESS  in [RTCMediaStream .cxx_destruct] method. 

![WebRTC_Crash.png…]()

Any suggestions ？

Thanks

**Comment by zevarito** [comment]
@gluckMu Hi,

Can you update the screenshot link? Image is not displayed, would be helpful to see the full stack of the crash.
It looks like some object got cleaned up early, perhaps you need to look at your retention/release cycles in property definitions and blocks.

Please don't rely on the example app because it is just a quick demo not an app, the purpose of that example is to show some API concepts and how delegates are called, not more.

**Comment by gluckMu** [comment]
@zevarito , thanks for your reply. I have solved this problem. I modified the dealloc of ECStream class and the crash doesn't appear again. 

`- (void)dealloc {
  _mediaStream = nil;
}`

I tested and found that the RTCPeerConnectionFactory object cannot be released before RTCMediaStream. Otherwise, a crash would happen. 

I have read the source code of WebRTC, but I am not familiar with C++, so I haven't found more details.

![crash](https://cloud.githubusercontent.com/assets/6963867/24227658/b2b96bea-0fa9-11e7-884f-6ba902794995.png)

**Comment by bigbangvn** [comment]
I also get the same crash if not set _localVideoTrack = nil in dealloc (https://github.com/bigbangvn/AppRTCMobile-iOS). And still don't understand why. It seems there's a problem with the scoped_ptr when incorporate with Objective-C code
