### ISSUE TITLE
Support for ipv6 mobile network

### ISSUE THREAD

**Issue by waqasburney** [zevarito/Licode-ErizoClientIOS#57]
We are facing an issue where we are unable to get video to work for us on iPhone when connecting using T-Mobile's network. This started happening after the 28.3 carrier update and I suppose it is being caused by the ipv6 only implementation that T-Mobile uses. Not sure if this a problem with the Licode server implementation or the client itself. Is anyone else facing this issue or have any idea how to resolve?

**Comment by zevarito** [comment]
Yup, I don't think the issue is related with the library. I think is a shared responsibility between WebRTC and Licode. Please take a look at this issue[0]. Also not sure if it should be an issue while Licode doesn't support IPv6 as long you have a TURN server to relay on, so not the best scenario but at least you should be able to connect media on both ends.

[0] https://bugs.chromium.org/p/webrtc/issues/detail?id=7703#c9

**Comment by zevarito** [comment]
@waqasburney I've submitted a patched release 60.4.0.1 can you try and report back if it works?
