### ISSUE TITLE
Any suggestions for porting Licode-ErizoClientIOS into Andriod?

### ISSUE THREAD

**Issue by jasonchuang** [zevarito/Licode-ErizoClientIOS#61]
Hi zevarito, thanks for your great work **Licode-ErizoClientIOS** to support conference call on mobile platform and we also want to support this client on Android as well, do you have any ideas or suggestions for moving the   [native android WebRTC](https://webrtc.org/native-code/android/) into ErizoClient enabled?
thanks

**Comment by zevarito** [comment]
Hi @jasonchuang, nice to hear you want to port it to Android.

I know about this outdated Android client[0] that you might want to look before start. Honestly never tried or even look at his codebase but it might help you as reference, but keep in mind that WebRTC API had changed in the last 3 years since the project seems to have been updated.

For the IOS library what I've done is to read WebRTC IOS code and kinda "reverse engineering" Licode's Erizo protocol reading the code and debugging websockets, I think you might get benefit from looking at ECSignalingChannel[1] class which basically implements that protocol.

The other part is the Public API that basically exposes the same as the Licode's Javascript API that is the one that talks with ECSignalingChannel[1].

If you have some particular question about the implementation, feel free to post here and I'll try to help you.

Good luck and please announce on the Forum when you get something working ;)

[0] https://github.com/K-GmbH/licodeAndroidClient

[1] https://github.com/zevarito/Licode-ErizoClientIOS/blob/master/ErizoClient/rtc/ECSignalingChannel.m
